<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.qa.testcases.TestMultipleUsersReactivaterequestforFileserver" tests="6" time="36.192" ignored="0" failures="0" timestamp="04 Sep 2020 04:23:11 GMT" skipped="2" hostname="DESKTOP-AKV4U58" errors="1">
  <testcase name="tearDownMethod" time="0.420" classname="com.qa.testcases.TestMultipleUsersReactivaterequestforFileserver">
    <error type="java.lang.RuntimeException" message="Unexpected result for screenshot command: null">
      <![CDATA[java.lang.RuntimeException: Unexpected result for screenshot command: null
	at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:395)
	at com.qa.utility.Helper.captureScreenshot(Helper.java:19)
	at com.qa.pages.BaseClass.tearDownMethod(BaseClass.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:712)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- tearDownMethod -->
  <testcase name="enterrequestInfo" time="9.973" classname="com.qa.testcases.TestMultipleUsersReactivaterequestforFileserver"/>
  <testcase name="entersecondUserDetails" time="0.003" classname="com.qa.testcases.TestMultipleUsersReactivaterequestforFileserver">
    <skipped/>
  </testcase> <!-- entersecondUserDetails -->
  <testcase name="enterfileserveraccess" time="14.605" classname="com.qa.testcases.TestMultipleUsersReactivaterequestforFileserver"/>
  <testcase name="enterfirstUserDetails" time="0.002" classname="com.qa.testcases.TestMultipleUsersReactivaterequestforFileserver">
    <skipped/>
  </testcase> <!-- enterfirstUserDetails -->
  <testcase name="checkvalidUser" time="11.189" classname="com.qa.testcases.TestMultipleUsersReactivaterequestforFileserver"/>
</testsuite> <!-- com.qa.testcases.TestMultipleUsersReactivaterequestforFileserver -->
